[target.xtensa-esp32-none-elf]
runner = "espflash flash --chip esp32 --baud 460800 --monitor --log-format serial"
# runner = "espflash flash --monitor --chip esp32"
# runner = "espflash flash --chip esp32 --monitor"

[env]
ESP_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
